project:
  type: website

website:
  title: "What Can You Do With AI?"
  description: "Let's Find Out"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/liuaoraymond
      - icon: linkedin
        href: https://linkedin.com/in/liuaoray/
    
format:
  html:
    theme: brite
    css: styles.css
   

execute:
  freeze: auto


